### ISSUE TITLE
CC65 doesn't like nosMemRealloc declaration

### ISSUE THREAD

**Issue by ssuukk** [picoos/picoos#12]
Existing source:

NANOEXT void POSCALL* nosMemRealloc(...)

Thinks it's a function pointer and fails with "wrong call convention" or whatever.

Compiles ok after changing to:

NANOEXT void* POSCALL nosMemRealloc(...)

As in other memory functions.

**Comment by AriZuu** [comment]
Fix is at cc65-realloc branch now.

**Comment by AriZuu** [comment]
Merged now.
