### ISSUE TITLE
Create user-visible taskid field in  POSTASK_t

### ISSUE THREAD

**Issue by ssuukk** [picoos/picoos#14]
It would be great to have a (probably optional/configurable) public taskId field in POSTASK_t structure, that would just keep an int with autoincremented task id. It can come in handy in many situations, like i.e. this tiny exception handling library:

https://github.com/ThrowTheSwitch/CException/blob/master/docs/CException.md

Look at: EXCEPTION_GET_ID there...

**Comment by AriZuu** [comment]
You can use the value of POSTASK_t pointer as task ID, they are unique. I do it that way where I need to list tasks, for example.

**Comment by ssuukk** [comment]
And how do you list all current tasks, btw?

**Comment by AriZuu** [comment]
There is "ts" command in eshell:

https://github.com/AriZuu/eshell/blob/master/show.c

**Comment by ssuukk** [comment]
What about Picoses with 

#define NOSCFG_FEATURE_REGISTRY    0

?

**Comment by AriZuu** [comment]
In eshell, there are versions of "ts" for cases without registry. Same thing can be done with POS_DEBUGHELP without nano layer.

**Comment by ssuukk** [comment]
OK, I guess I can live with that. Please close it. But I have another...
