### ISSUE TITLE
Error while trying to compile a slightly modified 6502 port

### ISSUE THREAD

**Issue by ssuukk** [picoos/picoos#15]
All I've changed in 6502 config was:

#define NOSCFG_FEATURE_REALLOC       1

As advised this requires:

#define NOSCFG_MEM_MANAGE_MODE       1

When trying to build my app I get:

../../inc/pos_nano.h(88): Error: Macro redefinition is not identical

88 is:

#define NOS_TASKDATA  void *nosstkroot;

Note that I didn't touch anything about NOS_TASKDATA.

I can provide you whole source as a zip if you want to investigate.

**Comment by AriZuu** [comment]
Odd, my small test app seems to compile ok with those set to 1. If you put your source somewhere I can download it from I'll try to take a look.

**Comment by ssuukk** [comment]
http://gofile.me/6EU0j/dWxJGuu7T

There's the project dir:

exception_task

(btw - I was unable to use the makefile provided in "make" dir, as described in docs, it complains "there's nothing to do for all", but was able to use the one from "apps", which works OK. Also I don't have an idea if I have to apply NANO=1 on SRC_TEXT level or on a single line by itself - what's the difference?)

...And theres "port__6502t" dir, with modified C64 config.

When I use NANO=1 by itself the error is gone, I think, but now I'm missing heap_start and heap_end, probably because they're not defined in default c64 config of cc65...

**Comment by AriZuu** [comment]
I think you should use the Makefile from apps to build a full binary. The makefile on the top level is for building picoos library only (it's invoked by app Makefile). You should have NANO=1 on separate line to set that variable in Makefile. Without that the Makefile won't compile the nano layer at all.

Dynamic memory routines need __heap_start and __heap_end to work. These variables tell the routines which area in memory can be used for heap. To fix this, you have two alternatives:

1. define NOSCFG_MEM_MANAGER_TYPE 0. This means that your cc65 runtime library must provide a working malloc & free.
2. define __heap_start and __heap_end. Easiest way is to create a static char array variable of size you'll need for heap. ie. something like:

static char heap_area[1024];
__heap_start = heap_area;
__heap_end = heap_area + sizeof(heap_area);

I was able to download your code, but maybe you could try these first if it solves the problem ?

**Comment by ssuukk** [comment]
Yep, I've figured it out about NANO=1. And I guess I should be able to get heap start end heap end symbols from if I create heap entry in cc65 config files.

As for the make, the docs say: "or copy and rename the file outfile.mak from the examples/make directory" - that didn't work for me. But the one from examples/apps - did.

**Comment by AriZuu** [comment]
After copying outfile.mak to Makefile, check values of
- RELROOT
- PORT
- NANO
- TARGET
- SRC_TXT
- DIR_CONFIG (I usually set thos to $(CURRENTDIR) so poscfg.h and noscfg.h are looked up from same directory as source

After that, things should just work.

**Comment by AriZuu** [comment]
About __heap_start & __heap_end: You cannot point these to same area that runtime library is using for heap. That might cause problems if runtime library uses internal malloc/free for something and pico]OS used the same area at same time.

I usually setup these variables in startup code, which runs before main(). I don't know if that is possible in cc65. If not, using static char array should work just fine.

**Comment by AriZuu** [comment]
@ssuukk did you figure this one out ? I'll close this if so.

**Comment by ssuukk** [comment]
Please close.

pt., 30 paź 2020, 11:54 użytkownik Ari Suutari <notifications@github.com>
napisał:
